#========================================================================================================================
# Cron: min (0 - 59) / hour (0 - 23) / day of month (1 - 31) / month (1 - 12) / day of week (0 - 6)(Sunday - Saturday)
#========================================================================================================================
#CI项目名
name: K2T纯AP固件-ImmortalWrt【802.11kvr漫游版】

on:
  workflow_dispatch:
    inputs:
      theme:
        description: '主题'      
        required: true
        default: 'material' 
        type: choice
        options:
        - material
        - argon

      OP_IP:
        description: 'AP默认管理IP (需与hAP ax3同网段但不冲突)'      
        required: true
        default: '192.168.88.2'
        type: string
        
      OP_router:
        description: '路由器类型'      
        required: true
        default: '旁路由'  # AP 模式等同于旁路由/网桥模式，关闭默认WAN/DHCP服务
        type: choice
        options:
        - 旁路由
        - 主路由

permissions: write-all

jobs:
  core_config:
    #调用公用编译核心OWRT-CORE.yml
    uses: ./.github/workflows/union-core.yml
    with:
      #编译平台
      CORE_TARGET: Phicomm_K2T
      #默认主题
      CORE_THEME: ${{ github.event.inputs.theme }}
      #默认主机名
      CORE_NAME: K2T-AP
      #默认密码
      CORE_PW: password
      #默认管理IP (推荐填入你网络规划中的 AP 固定静态 IP)
      CORE_IP: ${{ github.event.inputs.OP_IP }}
      #默认源码 (ImmortalWrt 针对无线驱动优化较好，非常适合做 AP)
      CORE_URL: https://github.com/immortalwrt/immortalwrt
      #源码版本
      CORE_BRANCH: openwrt-24.10
      CORE_tag_name: K2T-AP-kvr
      # 头部 配置文件 --- header 目录
      CORE_header: ath79_generic_DEVICE_phicomm_k2t.config
      # 配置文件 -- config 目录 (即你刚才修改好的配置文件)
      CORE_config: k2-K2t.config
      # 补丁脚本 -- patch 目录 不执行: false
      CORE_patch: false
      CORE_patch_after: false
      CORE_SOC_P1_SH: false
      CORE_SOC_P2_SH: false
      ########################################################
      # 通用脚本 -- Scripts 目录
      # 自定义扩展源定义
      CORE_DIY_P1_SH: K2.sh
      ########################################################
      # 固件通用设置
      CORE_DIY_P2_SH: Settings.sh
      ########################################################
      # soc初始化
      CORE_DIY_P3_SH: universal_init.sh
      ########################################################
      ## 彻底禁用 OpenClash / 科学上网相关脚本处理
      CORE_DIY_P4_SH: false
      # 删除不兼容的插件
      CORE_remove: false
      # 修正files配置文件脚本
      CORE_Files_SH: edit_files.sh
      # linux 内核
      CORE_LINUX: 5.15.x
      # 固件初始预设文件目录
      CORE_FILES: k2t/files
      # 打包设置 (K2T 为 MIPS 架构闪存直刷，无需 ophub 的打包打包逻辑)
      kernel_repo: ophub/kernel
      kernel_usage: stable
      builder_name: ophub
      auto_kernel: false
      CORE_Pack: false
      CORE_feeds_conf: false
      #######################################################
      # 明确关闭 OpenClash 逻辑
      CORE_META: false
      #######################################################
      # 传入旁路由/AP模式参数
      OP_router: ${{ github.event.inputs.OP_router }}
