#云编译公用核心
name: 【联合编译公用核心】

on:
  #公用核心标识
  workflow_call:
    inputs:
      CORE_TARGET:
        required: true
        type: string
      CORE_THEME:
        required: true
        type: string
      CORE_NAME:
        required: true
        type: string
      CORE_URL:
        required: true
        type: string
      CORE_PW:
        required: true
        type: string
      CORE_IP:
        required: true
        type: string
      CORE_BRANCH:
        required: true
        type: string
      CORE_tag_name:
        required: true
        type: string
      CORE_header:
        required: true
        type: string
      CORE_config:
        required: true
        type: string
      CORE_patch:
        required: true
        type: string
      CORE_patch_after:
        required: true
        type: string
      CORE_SOC_P1_SH:
        required: true
        type: string
      CORE_SOC_P2_SH:
        required: true
        type: string
      CORE_DIY_P1_SH:
        required: true
        type: string
      CORE_DIY_P2_SH:
        required: true
        type: string
      CORE_DIY_P3_SH:
        required: true
        type: string
      CORE_DIY_P4_SH:
        required: true
        type: string
      CORE_remove:
        required: true
        type: string
      CORE_LINUX:
        required: true
        type: string
      CORE_FILES:
        required: true
        type: string
      kernel_repo:
        required: true
        type: string
      kernel_usage:
        required: true
        type: string
      builder_name:
        required: true
        type: string
      auto_kernel:
        required: true
        type: string
      CORE_Pack:
        required: true
        type: string
      CORE_feeds_conf:
        required: true
        type: string
      CORE_META:
        required: true
        type: string
      CORE_Files_SH:
        required: true
        type: string
      OP_router:
        required: true
        type: string
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  CORE_TARGET: ${{inputs.CORE_TARGET}}
  CORE_THEME: ${{inputs.CORE_THEME}}
  CORE_NAME: ${{inputs.CORE_NAME}}
  CORE_URL: ${{inputs.CORE_URL}}
  CORE_PW: ${{inputs.CORE_PW}}
  CORE_IP: ${{inputs.CORE_IP}}
  CORE_BRANCH: ${{inputs.CORE_BRANCH}}
  CORE_tag_name: ${{inputs.CORE_tag_name}}
  CORE_header: header/${{inputs.CORE_header}}
  CORE_config: Config/${{inputs.CORE_config}}
  CORE_patch: patch/${{inputs.CORE_patch}}
  CORE_patch_after: patch/${{inputs.CORE_patch_after}}
  CORE_SOC_P1_SH: soc/${{inputs.CORE_SOC_P1_SH}}
  CORE_SOC_P2_SH: soc/${{inputs.CORE_SOC_P2_SH}}
  CORE_DIY_P1_SH: Scripts/${{inputs.CORE_DIY_P1_SH}}
  CORE_DIY_P2_SH: Scripts/${{inputs.CORE_DIY_P2_SH}}
  CORE_DIY_P3_SH: Scripts/${{inputs.CORE_DIY_P3_SH}}
  CORE_DIY_P4_SH: Scripts/${{inputs.CORE_DIY_P4_SH}}
  CORE_remove: remove/${{inputs.CORE_remove}}
  CORE_LINUX: ${{inputs.CORE_LINUX}}
  CORE_FILES: patch/${{inputs.CORE_FILES}}
  kernel_repo: ${{inputs.kernel_repo}}
  kernel_usage: ${{inputs.kernel_usage}}
  builder_name: ${{inputs.builder_name}}
  auto_kernel: ${{inputs.auto_kernel}}
  CORE_Pack: ${{inputs.CORE_Pack}}
  CORE_feeds_conf: patch/${{inputs.CORE_feeds_conf}}
  CORE_META: ${{inputs.CORE_META}}
  CORE_Files_SH: remove/${{inputs.CORE_Files_SH}}
  OP_router: ${{inputs.OP_router}}
  TZ: Asia/Shanghai

jobs:
  union_core:
    runs-on: ubuntu-latest
    steps:
      - name: 清理服务器空间(Ubuntu)
        uses: rmoyulong/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: true

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
        
      - name: 项目检查
        uses: actions/checkout@main

      - name: 最大化编译空间
        uses: rmoyulong/maximize-build-space@master
        with:
          root-reserve-mb: 2048
          swap-size-mb: 1024
          build-mount-path: /workdir
          overprovision-lvm: 'true'
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: 检查分配的服务器性能
        run: |
          echo "警告⚠"
          echo "分配的服务器性能有限，若选择的插件过多，务必注意CPU性能！"
          echo -e "已知CPU型号（降序）： 9V74 7763，8370C，8272CL，8171M，E5-2673 \n"
          echo "--------------------------CPU信息--------------------------"
          echo "CPU物理数量：$(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
          echo -e "CPU核心信息：$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c) \n"
          echo "--------------------------内存信息--------------------------"
          echo "已安装内存详细信息："
          echo -e "$(sudo lshw -short -C memory | grep GiB) \n"
          echo "--------------------------硬盘信息--------------------------"
          echo "硬盘数量：$(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT   

      - name: 初始化编译环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -qq update --fix-missing
          sudo -E apt-get -qq full-upgrade
          
          if [[ "${{ inputs.CORE_BRANCH }}" == *"openwrt-24.10"* ]]; then
            sudo -E apt-get -qq install -y $(curl -fsSL https://raw.githubusercontent.com/rmoyulong/AX6-Actions_Lede/master/Ubuntu-2410.txt)
           else
            sudo -E apt-get -y install $(cat $GITHUB_WORKSPACE/Ubuntu-2204.txt)           
          fi
          
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo -E systemctl daemon-reload
          sudo timedatectl set-timezone "$TZ"
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
          echo "status=success" >> ${GITHUB_OUTPUT}
          df -Th              

      - name: 初始化变量
        run: |
          export CORE_DATE=$(TZ=UTC-8 date +"%y.%m.%d_%H.%M.%S")
          export CORE_SOURCE=$(echo $CORE_URL | cut -d '/' -f 5-)
          
          echo "CORE_SOURCE=$CORE_SOURCE" >> $GITHUB_ENV
          echo "CORE_TARGET=$CORE_TARGET" >> $GITHUB_ENV
          echo "CORE_DATE=$CORE_DATE" >> $GITHUB_ENV
          echo "CORE_PW=$CORE_PW" >> $GITHUB_ENV
          echo "CORE_IP=$CORE_IP" >> $GITHUB_ENV
          echo "CORE_BRANCH=$CORE_BRANCH" >> $GITHUB_ENV
          echo "CORE_tag_name=$CORE_tag_name" >> $GITHUB_ENV
          echo "CORE_header=$CORE_header" >> $GITHUB_ENV
          echo "CORE_config=$CORE_config" >> $GITHUB_ENV
          echo "CORE_patch=$CORE_patch" >> $GITHUB_ENV
          echo "CORE_patch_after=$CORE_patch_after" >> $GITHUB_ENV
          echo "CORE_SOC_P1_SH=$CORE_SOC_P1_SH" >> $GITHUB_ENV
          echo "CORE_SOC_P2_SH=$CORE_SOC_P2_SH" >> $GITHUB_ENV
          echo "CORE_DIY_P1_SH=$CORE_DIY_P1_SH" >> $GITHUB_ENV
          echo "CORE_DIY_P2_SH=$CORE_DIY_P2_SH" >> $GITHUB_ENV
          echo "CORE_DIY_P3_SH=$CORE_DIY_P3_SH" >> $GITHUB_ENV
          echo "CORE_DIY_P4_SH=$CORE_DIY_P4_SH" >> $GITHUB_ENV
          echo "CORE_remove=$CORE_remove" >> $GITHUB_ENV
          echo "CORE_LINUX=$CORE_LINUX" >> $GITHUB_ENV
          echo "CORE_FILES=$CORE_FILES" >> $GITHUB_ENV
          echo "kernel_repo=$kernel_repo" >> $GITHUB_ENV
          echo "kernel_usage=$kernel_usage" >> $GITHUB_ENV
          echo "builder_name=$builder_name" >> $GITHUB_ENV
          echo "auto_kernel=$auto_kernel" >> $GITHUB_ENV
          echo "CORE_Pack=$CORE_Pack" >> $GITHUB_ENV
          echo "CORE_feeds_conf=$CORE_feeds_conf" >> $GITHUB_ENV
          echo "CORE_THEME=$CORE_THEME" >> $GITHUB_ENV
          echo "CORE_META=$CORE_META" >> $GITHUB_ENV
          echo "CORE_Files_SH=$CORE_Files_SH" >> $GITHUB_ENV
          echo "OP_router=$OP_router" >> $GITHUB_ENV
          
          echo "CORE_META: $CORE_META"
          echo "CORE_IP: $CORE_IP"
          echo "CORE_THEME: $CORE_THEME"
          echo "OP_router: $OP_router"
          
          # 使用正则表达式校验IP地址格式是否符合规范
          if [[ $CORE_IP =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "IP地址 $CORE_IP 符合规范。"
          else
            echo "IP地址 $CORE_IP 不符合规范。"
            exit 1
          fi
  
      - name: 检查脚本
        run: |
          dos2unix ./Scripts/*.sh
          chmod +x ./Scripts/*.sh
          
          dos2unix ./soc/*.sh
          chmod +x ./soc/*.sh
          
          dos2unix ./patch/*.sh
          chmod +x ./patch/*.sh
          
          dos2unix ./remove/*.sh
          chmod +x ./remove/*.sh
          

      - name: 克隆源码库
        id: codes
        working-directory: /workdir        
        run: |
          # Set up compilation source code
          REPO_URL="${{ inputs.CORE_URL }}"
          REPO_BRANCH="${{ inputs.CORE_BRANCH }}"
          
          df -hT $PWD
          git clone -q --single-branch --depth=1 --branch=${REPO_BRANCH} ${REPO_URL} openwrt
          ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
  
      - name: 加载自定义订阅源
        run: |
          cd openwrt
         
          if [[ "${{ inputs.CORE_feeds_conf }}" == *"false"* ]]; then
            echo "使用默认feeds.conf.default文件"
          else
            cp -rf $GITHUB_WORKSPACE/${{ env.CORE_feeds_conf }} ./feeds.conf.default
          fi
          
      - name: 前置补丁
        run: |
          if [[ "${{ inputs.CORE_patch }}" == *"false"* ]]; then
            echo "不需要打前置补丁"
          else
            ${GITHUB_WORKSPACE}/${CORE_patch}
          fi

      - name: 启动缓存[第二次起生效]
        uses: rmoyulong/cachewrtbuild@main
        with:
          ccache: 'true'
          prefix: ${{ github.workspace }}/openwrt
          mixkey: ${{ env.CORE_SOURCE }}/tree/${{ env.CORE_TARGET }}?device=${{ env.CORE_header }}-${{ env.CORE_config }}
          
      - name: 更新订阅源
        run: |
          cd openwrt
          
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
      - name: 后置补丁
        run: |
          if [[ "${{ inputs.CORE_patch_after }}" == *"false"* ]]; then
            echo "不需要打后置补丁"
          else
            ${GITHUB_WORKSPACE}/${CORE_patch_after}
          fi
         
      - name: 通用脚本
        run: |
          cd openwrt
          
          if [[ "${{ inputs.CORE_DIY_P1_SH }}" == *"false"* ]]; then
            echo "不需要执行 CORE_DIY_P1_SH"
          else
            ${GITHUB_WORKSPACE}/${CORE_DIY_P1_SH}
          fi          
          echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV
          
          curl -L -o package/base-files/files/etc/banner https://raw.githubusercontent.com/rmoyulong/AX6-Actions_Lede/master/ax6/cats_banner
          ${GITHUB_WORKSPACE}/${CORE_DIY_P2_SH} "${{ env.CORE_IP }}" "${{ env.CORE_NAME }}" "${{ env.CORE_THEME }}" "${{ env.CORE_SOURCE }}"
          
          if [[ "${{ inputs.CORE_DIY_P3_SH }}" == *"false"* ]]; then
            echo "不需要执行 CORE_DIY_P3_SH"
          else
            ${GITHUB_WORKSPACE}/${CORE_DIY_P3_SH} "${CORE_FILES}" "${CORE_header}" "${{ env.CORE_SOURCE }}"
          fi
          
          if [[ "${{ inputs.CORE_DIY_P4_SH }}" == *"false"* ]]; then
            echo "不需要执行 CORE_DIY_P4_SH"
          else
            ${GITHUB_WORKSPACE}/${CORE_DIY_P4_SH} "${{ inputs.CORE_META }}" "${{ inputs.CORE_IP }}"
          fi 

      - name: 删除冲突的插件
        run: |
          cd openwrt
          
          if [[ "${{ inputs.CORE_remove }}" == *"false"* ]]; then
            echo "不需要执行 CORE_remove"
          else
            ${GITHUB_WORKSPACE}/${CORE_remove}
          fi
          
      - name: 拷贝编译配置文件和插件初始化文件
        run: |
          cd openwrt
          
          #如果files文件夹不存在，创建文件夹
          if [ ! -d "./files" ]; then
            mkdir ./files
          fi
          [ -e $GITHUB_WORKSPACE/$CORE_FILES ] && cp -rf $GITHUB_WORKSPACE/$CORE_FILES/* ./files
          
          rm -rf ./tmp* ./.config*
          rm -rf ./.config
          
          if [[ "${{ inputs.CORE_header }}" == *"false"* ]]; then
             echo "没有header config文件"
             cat ${GITHUB_WORKSPACE}/${CORE_config}  > .config
          else
             cat $GITHUB_WORKSPACE/${CORE_header}  > .config
             cat $GITHUB_WORKSPACE/${CORE_config} >> .config
          fi
          #cat .config          

      - name: 修正files文件配置
        run: |
          cd openwrt
          
          if [[ "${{ inputs.CORE_Files_SH }}" == *"false"* ]]; then
            echo "不需要执行 CORE_Files_SH"
          else
            ${GITHUB_WORKSPACE}/${CORE_Files_SH} "$OP_router" "$CORE_NAME" "${{ inputs.CORE_IP }}"
            echo $OP_router
            echo $CORE_header
          fi
          
      - name: 下载编译依赖
        working-directory: ./openwrt
        run: |
          make defconfig
          make download -j$(( $(nproc) * 2 ))
          find dl -size -1k -exec rm -f {} \;

      - name: 编译固件
        working-directory: ./openwrt
        run: |     
          echo -e "$(nproc) thread compile"
          make -j$(( $(nproc) + 1 )) || make -j1 V=s
          echo "status=success" >> $GITHUB_OUTPUT
          echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV 
 
      - name: 固件单独处理脚本
        run: |
          if [[ "${{ inputs.CORE_SOC_P1_SH }}" == *"false"* ]]; then
            echo "没有需要单独处理的脚本1"
          else
            ${GITHUB_WORKSPACE}/${CORE_SOC_P1_SH}
          fi
          
          if [[ "${{ inputs.CORE_SOC_P2_SH }}" == *"false"* ]]; then
            echo "没有需要单独处理的脚本2"
          else
            ${GITHUB_WORKSPACE}/${CORE_SOC_P2_SH}
          fi
          
      - name: 获得固件信息
        run: |
          cd openwrt/bin/targets/*/*
          kword=$(cat *.manifest | grep ^kernel | cut -d- -f2 | tr -d ' ')
          KERNEL=${kword%~*}
          echo "KERNEL=$KERNEL" >> $GITHUB_ENV
          cat sha256sums
          
      - name: 整理固件
        run: |
          cd openwrt && mkdir ./upload
          
          rm -rf $(find ./bin/targets/ -iregex ".*\(json\|manifest\|buildinfo\|sha256sums\|packages\)$")
          cp -rf $(find ./bin/targets/ -type f -iname "*.*") ./upload/
          cp -rf ./.config ./upload/Config.txt
          
          export CORE_DATE=$(TZ=UTC-8 date +"%y.%m.%d_%H.%M.%S")
          echo "CORE_DATE=$CORE_DATE" >> $GITHUB_ENV
          show_tag_name=${{env.CORE_TARGET}}_${{env.CORE_SOURCE}}_${{env.CORE_DATE}}
          echo "show_tag_name=$show_tag_name" >> $GITHUB_ENV
          #获得当前目录的路径信息
          cd ./upload
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV
          
          #如有.tar文件就转化为.gz
          files=$(ls *.tar 2> /dev/null | wc -l)
          if [ "$files" != "0" ]; then
            gzip *.tar
          fi

      - name: Armv8打包OpenWrt
        if: env.CORE_Pack == 'ophub'
        uses: ophub/amlogic-s9xxx-openwrt@main
        with:
          openwrt_path: openwrt/upload/*rootfs.tar.gz
          openwrt_board: ${{ env.CORE_TARGET }}
          openwrt_kernel: ${{ env.CORE_LINUX }}
          auto_kernel: ${{ inputs.auto_kernel }}
          kernel_repo: ${{ inputs.kernel_repo }}
          kernel_usage: ${{ inputs.kernel_usage }}
          builder_name: ${{ inputs.builder_name }}

      - name: 将编译的底包转换为OpenWrt
        if: env.CORE_Pack == 'flippy'
        uses: ophub/flippy-openwrt-actions@main
        env:
          OPENWRT_ARMVIRT: openwrt/upload/*rootfs.tar.gz
          PACKAGE_SOC: ${{ env.CORE_TARGET }}
          WHOAMI: moyulong
          KERNEL_VERSION_NAME: ${{ env.CORE_LINUX }}
          KERNEL_AUTO_LATEST: true
          GZIP_IMGS: .gz
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: 合并原始资料和打包文件
        if: env.CORE_Pack == 'ophub'  ||  env.CORE_Pack == 'flippy'
        run: |
          cp -f openwrt/upload/*.* ${{ env.PACKAGED_OUTPUTPATH }}/
          cd ${{ env.PACKAGED_OUTPUTPATH }}/
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV
          
      - name: 生成标签，上传固件
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{env.show_tag_name}}
          body: |
            ====================🧊固件信息🧊=======================
            ➦ 📒 固件名称：${{env.CORE_NAME}} ${{env.CORE_tag_name}}
            ➦ 💻 固件平台：${{ env.CORE_TARGET }}
            ➦ ⚽ 固件源码：${{ env.CORE_SOURCE }}
            ➦ 💝 源码分支：${{ env.CORE_BRANCH }}
            ➦ 🚀 内核版本：${{ env.KERNEL }}
            ➦ 🌐 默认地址：${{env.CORE_IP}}
            ➦ 🔑 默认密码：password            
          artifacts: ${{ env.FIRMWARE }}/*
          
      - name: 清理Releases
        uses: rmoyulong/delete-older-releases@master
        with:
          keep_latest: 16
          delete_tags: true

      - name: 清理Workflows
        uses: rmoyulong/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 1
